version: '3'
services:
  # api:                                  # 后端express容器
  #   container_name: juejin-api    
  #   restart: always                     # 重启策略: 容器退出时总是重启容器
  #   build:
  #     context: ./                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
  #     dockerfile: ./backend/Dockerfile
  #   working_dir: /app                   # 设置工作目录为容器内的app文件夹
  #   environment:
  #     TZ: Asia/Shanghai
  #   volumes:                            # 挂载文件
  #     - ./code-api:/app                 # 将主机的code-api文件夹(java代码)映射到容器内的app文件夹
  #     - ./logs/:/app/log                # 映射容器产生的日志到主机的logs文件夹
  #   ports:                              # 映射端口
  #     - "9101:9101"
  #   command: mvn clean spring-boot:run -Dspring-boot.run.profiles=dev '-Dmaven.test.skip=true' # 容器创建后执行命令运行springboot项目

  web:                                  # 前端web容器(运行nginx中的React项目)
    container_name: juejin-web    
    restart: always                     
    build:
      context: ./                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: frontend/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3000:3000"                      # 映射端口
    # depends_on:                          # 依赖于api容器，被依赖容器启动后此web容器才可启动
    #   - api