version: '3'
services:
# helper-web:  #前端项目的service name
#     container_name: 'helper-web-container'  #容器名称
#     image: nginx  #指定镜像
#     restart: always
#     ports:
#     - 80:80
#     volumes: 
#     - ./nginx.conf:/etc/nginx/nginx.conf  #挂载nginx配置
#     - ./dist:/usr/share/nginx/html/    #挂载项目
#     depends_on:
#     - helper-server
helper-server:    #后端项目的service name
    container_name: 'helper-server-container'
    build: ./backend  #根据server目录下面的Dockerfile构建镜像
    restart: always
    expose:
    - 8001