version: '3'
services:
  api:                                  # 后端express容器
    container_name: juejin-api  
    image: 58fe/58fe.com:latest  
    restart: always                     # 重启策略: 容器退出时总是重启容器
    build:
      context: ./                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: ./backend/Dockerfile
    working_dir: ./backend                   # 设置工作目录为容器内的app文件夹
    environment:
      TZ: Asia/Shanghai
    volumes:                            # 挂载文件
      - .:/juejin/backend                
    ports:                              # 映射端口
      - "8001:8001"
    command:  node ./backend/dist/app # 容器创建后执行命令 

  web:                                  # 前端web容器(运行nginx中的React项目)
    container_name: juejin-web    
    restart: always                     
    build:
      context: ./                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: frontend/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3000:3000"                      # 映射端口
    depends_on:                          # 依赖于api容器，被依赖容器启动后此web容器才可启动
      - api